name: Move new pull request to "Ongoing development" project

on:
  pull_request:
    types:
      - opened

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.5.1
        continue-on-error: true
        with:
          project: Ongoing development
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN }}
